name: Release Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
  contents: write

jobs:
  build:
    name: Build for Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate file structure
      run: |
        python build_gameFolders.py

    - name: Create zip file
      run: |
        zip -r release.zip -@ < release_build_files.txt
      shell: bash

    - name: Run semantic-release
      id: semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #*Runs semantic release, then checks if the output claims there are no relevant changes.
      #*The && statement ensures SKIP_UPLOAD is only set to true if the no relevant changes string is found
      run: |
        npx semantic-release
        if grep -q "There are no relevant changes, so no new version is released."; then
          echo "SKIP_UPLOAD=true" >> $GITHUB_ENV
        fi

    - name: Capture version
      run: echo "VER=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      id: set_version
      continue-on-error: true

    - name: Push to itch.io
      #*Only execute this step we didn't decide to skip upload
      if:  env.SKIP_UPLOAD != 'true'
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        ITCH_USER: ThanaThan
        ITCH_GAME: terminal-void
        CHANNEL: HTML5
        VERSION: ${{ env.VER }}
        PACKAGE:  release.zip